<?php
declare(strict_types=1); require dirname(__DIR__).'/src/bootstrap.php';
$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH);$method=$_SERVER['REQUEST_METHOD'];
try {
 if($method==='OPTIONS') out(['ok'=>true]);
 ensure_product_columns();
 if($path==='/api/catalogo'&&$method==='GET'){ $rows=pg()->query("SELECT p.id,p.legacy_id AS legacy_id,p.sku,p.barcode,p.name,p.description,p.sale_price AS price,p.unit_code AS unit,COALESCE(c.name,'Otros') AS category,COALESCE(s.quantity,0) AS stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN product_stock s ON s.product_id=p.id AND s.warehouse_id=20 WHERE p.active ORDER BY p.name")->fetchAll(); out(['ok'=>true,'products'=>$rows]); }
 if($path==='/api/config/productos'&&$method==='POST'){ $v=body();$name=trim((string)($v['name']??''));$price=(float)($v['price']??0);$cat=trim((string)($v['category']??'Otros'));$desc=trim((string)($v['description']??'Producto creado desde Papachito'));if($name===''||$price<0)out(['ok'=>false,'message'=>'Nombre y precio válidos requeridos'],422);$db=pg();$db->beginTransaction();$c=$db->prepare("INSERT INTO categories(name) VALUES(?) ON CONFLICT(name) DO UPDATE SET active=TRUE RETURNING id");$c->execute([$cat]);$cid=(int)$c->fetchColumn();$p=$db->prepare('INSERT INTO products(category_id,name,description,unit_code,sale_price,active) VALUES(?,?,?,?,?,TRUE) RETURNING id');$p->execute([$cid,$name,$desc,'NIU',$price]);$id=(int)$p->fetchColumn();$s=$db->prepare('INSERT INTO product_stock(product_id,warehouse_id,quantity) VALUES(?,?,?) ON CONFLICT(product_id,warehouse_id) DO NOTHING');$s->execute([$id,20,0]);$db->commit();out(['ok'=>true,'id'=>$id]); }
 if(preg_match('#^/api/config/productos/(\d+)$#',$path,$m)&&$method==='DELETE'){ $st=pg()->prepare('UPDATE products SET active=FALSE,updated_at=CURRENT_TIMESTAMP WHERE id=? RETURNING id');$st->execute([(int)$m[1]]);out(['ok'=>(bool)$st->fetchColumn()]); }
 if($path==='/api/ventas/sincronizar'&&$method==='POST'){ $v=body();$items=$v['items']??[];$seller=trim((string)($v['seller']??''));$localId=(string)($v['id']??'');if($seller===''||$localId===''||!is_array($items)||count($items)===0)out(['ok'=>false,'message'=>'Venta incompleta'],422);$uuid=stable_uuid($localId);$db=pg();$exists=$db->prepare('SELECT id FROM sales WHERE sale_uuid=?');$exists->execute([$uuid]);if($exists->fetchColumn())out(['ok'=>true,'uuid'=>$uuid,'duplicate'=>true]);$total=0.0;foreach($items as $it){$qty=max(0,(float)($it['quantity']??1));$price=max(0,(float)($it['price']??0));$total+=$qty*$price;}if($total<=0)out(['ok'=>false,'message'=>'Total invalido'],422);$created=(string)($v['createdAt']??date('c'));$soldAt=date('Y-m-d H:i:sP',strtotime($created)?:time());$saleDate=date('Y-m-d',strtotime($created)?:time());$payCode=(($v['paymentMethod']??'cash')==='digital')?'digital_wallet':'cash';$db->beginTransaction();$s=$db->prepare("INSERT INTO sales(sale_uuid,document_type,status,customer_document,customer_name,currency,sale_date,sold_at,total,amount_received,change_amount,original_payload) VALUES(?,?,?,?,?,?,?,?,?,?,?,?::jsonb) RETURNING id");$s->execute([$uuid,'03','completed','00000000','Varios','PEN',$saleDate,$soldAt,$total,$total,0,json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)]);$saleId=(int)$s->fetchColumn();$line=$db->prepare('INSERT INTO sale_items(sale_id,product_id,product_name,quantity,unit_price,line_total) VALUES(?,?,?,?,?,?)');$stock=$db->prepare('UPDATE product_stock SET quantity=quantity-?,updated_at=CURRENT_TIMESTAMP WHERE product_id=? AND warehouse_id=20');foreach($items as $it){$qty=max(0,(float)($it['quantity']??1));$price=max(0,(float)($it['price']??0));$name=trim((string)($it['name']??'Producto'));$pid=isset($it['id'])&&is_numeric($it['id'])?(int)$it['id']:null;$line->execute([$saleId,$pid,$name,$qty,$price,$qty*$price]);if($pid)$stock->execute([$qty,$pid]);}$pm=$db->prepare('SELECT id FROM payment_methods WHERE code=?');$pm->execute([$payCode]);$pmId=(int)$pm->fetchColumn();$p=$db->prepare('INSERT INTO sale_payments(sale_id,payment_method_id,amount) VALUES(?,?,?)');$p->execute([$saleId,$pmId,$total]);$a=$db->prepare("INSERT INTO audit_log(sale_uuid,action,details,ip_address) VALUES(?,'mobile_sync',?::jsonb,?)");$a->execute([$uuid,json_encode(['seller'=>$seller,'local_id'=>$localId],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),$_SERVER['REMOTE_ADDR']??null]);$db->commit();out(['ok'=>true,'uuid'=>$uuid,'total'=>$total]); }
 if($path==='/api/ventas'&&$method==='GET'){ $rows=pg()->query("SELECT sale_uuid AS uuid,legacy_cpe_id,document_type,series,document_number,status,sold_at,total FROM sales ORDER BY sold_at DESC LIMIT 100")->fetchAll();out(['ok'=>true,'sales'=>$rows]); }
 if($path==='/api/reportes'&&$method==='GET'){ $from=$_GET['desde']??date('Y-m-d');$to=$_GET['hasta']??$from;$st=pg()->prepare("SELECT COUNT(*) count,COALESCE(SUM(total),0) total FROM sales WHERE status='completed' AND sale_date BETWEEN ? AND ?");$st->execute([$from,$to]);$s=$st->fetch();$q=pg()->prepare("SELECT sale_date date,COUNT(*) count,COALESCE(SUM(total),0) total FROM sales WHERE status='completed' AND sale_date BETWEEN ? AND ? GROUP BY sale_date ORDER BY sale_date");$q->execute([$from,$to]);out(['ok'=>true,'from'=>$from,'to'=>$to,'summary'=>['count'=>(int)$s['count'],'total'=>(float)$s['total'],'average'=>(int)$s['count']?(float)$s['total']/(int)$s['count']:0],'series'=>$q->fetchAll()]); }
 out(['ok'=>false,'message'=>'Ruta no encontrada'],404);
} catch(Throwable $e){ out(['ok'=>false,'message'=>'Error interno de API'],500); }
