BEGIN;

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id BIGINT UNIQUE,
    name VARCHAR(120) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id BIGINT UNIQUE,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    sku VARCHAR(50),
    barcode VARCHAR(80),
    name VARCHAR(250) NOT NULL,
    description TEXT,
    unit_code VARCHAR(10) NOT NULL DEFAULT 'NIU',
    sale_price NUMERIC(14,2) NOT NULL CHECK (sale_price >= 0),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS products_name_idx ON products (name);
CREATE INDEX IF NOT EXISTS products_category_idx ON products (category_id);

CREATE TABLE IF NOT EXISTS product_stock (
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    warehouse_id INTEGER NOT NULL DEFAULT 20,
    quantity NUMERIC(14,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (product_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS payment_methods (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id INTEGER UNIQUE,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(80) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_uuid UUID NOT NULL UNIQUE,
    legacy_cpe_id BIGINT UNIQUE,
    document_type VARCHAR(4) NOT NULL DEFAULT '03',
    series VARCHAR(8),
    document_number BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','error','cancelled')),
    customer_document VARCHAR(20) NOT NULL DEFAULT '00000000',
    customer_name VARCHAR(150) NOT NULL DEFAULT 'Varios',
    currency CHAR(3) NOT NULL DEFAULT 'PEN',
    sale_date DATE NOT NULL,
    sold_at TIMESTAMPTZ NOT NULL,
    total NUMERIC(14,2) NOT NULL CHECK (total >= 0),
    amount_received NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount_received >= 0),
    change_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (change_amount >= 0),
    error_message TEXT,
    original_payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    cancelled_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (document_type, series, document_number)
);
CREATE INDEX IF NOT EXISTS sales_date_status_idx ON sales (sale_date, status);
CREATE INDEX IF NOT EXISTS sales_sold_at_idx ON sales (sold_at DESC);

CREATE TABLE IF NOT EXISTS sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES products(id) ON DELETE SET NULL,
    product_name VARCHAR(250) NOT NULL,
    quantity NUMERIC(14,2) NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
    line_total NUMERIC(14,2) NOT NULL CHECK (line_total >= 0)
);
CREATE INDEX IF NOT EXISTS sale_items_sale_idx ON sale_items (sale_id);
CREATE INDEX IF NOT EXISTS sale_items_product_idx ON sale_items (product_id);

CREATE TABLE IF NOT EXISTS sale_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id BIGINT NOT NULL REFERENCES sales(id) ON DELETE CASCADE,
    payment_method_id SMALLINT NOT NULL REFERENCES payment_methods(id),
    amount NUMERIC(14,2) NOT NULL CHECK (amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS sale_payments_sale_idx ON sale_payments (sale_id);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id),
    sale_id BIGINT REFERENCES sales(id) ON DELETE SET NULL,
    warehouse_id INTEGER NOT NULL DEFAULT 20,
    movement_type VARCHAR(20) NOT NULL CHECK (movement_type IN ('sale','cancellation','adjustment','opening')),
    quantity_delta NUMERIC(14,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS inventory_movements_product_idx ON inventory_movements (product_id, created_at DESC);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_uuid UUID,
    action VARCHAR(50) NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS audit_log_sale_uuid_idx ON audit_log (sale_uuid, created_at DESC);

CREATE OR REPLACE VIEW daily_sales AS
SELECT sale_date,
       COUNT(*) AS sales_count,
       COALESCE(SUM(total), 0)::NUMERIC(14,2) AS total
FROM sales
WHERE status = 'completed'
GROUP BY sale_date;

COMMIT;
