<?php
declare(strict_types=1);
$root='C:\\laragon\\www\\wilcatsystems_papachito';$e=[];foreach(file($root.'/.env',FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES) as $l){if(strpos($l,'=')===false)continue;[$k,$v]=explode('=',$l,2);$e[trim($k)]=trim(trim($v),"'\"");}$pw=getenv('PAPACHITO_PG_PASSWORD');if(!$pw)throw new RuntimeException('Define PAPACHITO_PG_PASSWORD');
$my=new PDO("mysql:host={$e['DB_HOST']};port={$e['DB_PORT']};dbname={$e['DB_DATABASE']};charset=utf8mb4",$e['DB_USERNAME'],$e['DB_PASSWORD'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$pg=new PDO('pgsql:host=127.0.0.1;port=5432;dbname=papachito_app','papachito_app',$pw,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
function uuidFor(int $id): string {$h=md5('papachito-cpe-'.$id);$h[12]='5';$h[16]=dechex((hexdec($h[16])&3)|8);return vsprintf('%s-%s-%s-%s-%s',[substr($h,0,8),substr($h,8,4),substr($h,12,4),substr($h,16,4),substr($h,20,12)]);}
$products=$pg->query('SELECT legacy_id,id FROM products')->fetchAll(PDO::FETCH_KEY_PAIR);$payments=$pg->query('SELECT legacy_id,id FROM payment_methods')->fetchAll(PDO::FETCH_KEY_PAIR);$pg->beginTransaction();try{
 $sale=$pg->prepare('INSERT INTO sales (sale_uuid,legacy_cpe_id,document_type,series,document_number,status,customer_document,customer_name,sale_date,sold_at,total,amount_received,change_amount,original_payload) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?::jsonb) ON CONFLICT (legacy_cpe_id) DO UPDATE SET total=EXCLUDED.total,status=EXCLUDED.status');
 $items=$pg->prepare('INSERT INTO sale_items (sale_id,product_id,product_name,quantity,unit_price,line_total) VALUES (?,?,?,?,?,?)');
 $pay=$pg->prepare('INSERT INTO sale_payments (sale_id,payment_method_id,amount) VALUES (?,?,?)');
 $map=[];$rows=$my->query('SELECT * FROM cpe_cabecera ORDER BY IdCpe_cabecera');foreach($rows as $r){$id=(int)$r['IdCpe_cabecera'];$cancel=(!empty($r['ccabaj'])||strtoupper((string)$r['est_sunat'])==='ANULADO');$status=$cancel?'cancelled':'completed';$date=substr((string)($r['ccafem']?:date('Y-m-d')),0,10);$sold=(string)($r['fecha_hora']?:$date.' 00:00:00');$total=max(0,(float)$r['ccaitv']);$received=max(0,(float)($r['efectivo']?:$total));$change=max(0,(float)($r['vuelto']?:0));$payload=json_encode(['legacy_id'=>$id,'document'=>$r['serdoc'].'-'.$r['numdoc']],JSON_UNESCAPED_UNICODE);$sale->execute([uuidFor($id),$id,(string)($r['tdocod']?:'03'),$r['serdoc']?:null,$r['numdoc']?:null,$status,'00000000',$r['ccanom']?:'Varios',$date,$sold,$total,$received,$change,$payload]);$row=$pg->prepare('SELECT id FROM sales WHERE legacy_cpe_id=?');$row->execute([$id]);$sid=(int)$row->fetchColumn();$map[$id]=$sid;}
 $pg->exec('DELETE FROM sale_payments WHERE sale_id IN (SELECT id FROM sales WHERE legacy_cpe_id IS NOT NULL)');
 $pg->exec('DELETE FROM sale_items WHERE sale_id IN (SELECT id FROM sales WHERE legacy_cpe_id IS NOT NULL)');
 foreach($my->query('SELECT * FROM cpe_detalle ORDER BY IdCpe_detalle') as $r){$sid=$map[(int)$r['IdCpe_cabecera']]??0;if(!$sid)continue;$name=trim((string)($r['cdedes']?:$r['pronomobs']?:'Producto'));$qty=max(0,(float)$r['cdecan']);$unit=max(0,(float)($r['cdepve']?:$r['cdevun']?:0));$line=round($qty*$unit,2);if($qty>0)$items->execute([$sid,$products[(int)$r['IdProducto']]??null,$name,$qty,$unit,$line]);}
 foreach($my->query('SELECT * FROM venta_medio_pago') as $r){$sid=$map[(int)$r['IdCpe_cabecera']]??0;$pm=$payments[(int)$r['id_med_pag']]??null;if($sid&&$pm)$pay->execute([$sid,$pm,max(0,(float)$r['monto'])]);}
 $pg->commit();echo json_encode(['ok'=>true,'sales'=>count($map)],JSON_UNESCAPED_UNICODE),PHP_EOL;
}catch(Throwable $x){$pg->rollBack();fwrite(STDERR,$x->getMessage().PHP_EOL);exit(1);}
